CREATE DATABASE IF NOT EXISTS PFSwChO;
CREATE TABLE IF NOT EXISTS PFSwCho.dane
(
    id MEDIUMINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(30),
    surname VARCHAR(30),
    age INT(3),
    PRIMARY KEY (id)
)